<?php

namespace Database\Seeders\Legacy;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Student;
use App\Models\Enrollment;
use App\Models\Course;

class Kinder2025Seeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            $course = Course::whereHas('gradeLevel', fn ($q) =>
                $q->where('name', 'Kinder')
            )->where('school_year', 2026)->firstOrFail();

            $students = [

                [
                    'rut' => '26.878.266-4',
                    'first_name' => 'Yordana Liset',
                    'last_name_father' => 'Gaete',
                    'last_name_mother' => 'Ramos',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-04-12',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Putreguel S/N',
                    'commune' => 'Máfil',
                    'phone' => '9970044505',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.897.436-9',
                    'first_name' => 'Julieta',
                    'last_name_father' => 'Abarca',
                    'last_name_mother' => 'Amaya',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-07-01',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Parcelación Doña Inés, Ruta T-305',
                    'commune' => 'Máfil',
                    'phone' => '990372862',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.911.490-8',
                    'first_name' => 'Mateo',
                    'last_name_father' => 'Leandro',
                    'last_name_mother' => null,
                    'gender' => 'Masculino',
                    'birth_date' => '2019-07-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Iñaque Huerto N°11',
                    'commune' => 'Máfil',
                    'phone' => '9811960518',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.803.848-3',
                    'first_name' => 'Julieta Amelia',
                    'last_name_father' => 'Álvarez',
                    'last_name_mother' => 'Peña',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-04-20',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Sector Runca S/N',
                    'commune' => 'Máfil',
                    'phone' => '942915212',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.246.216-k',
                    'first_name' => 'Mia Isabella',
                    'last_name_father' => 'Arias',
                    'last_name_mother' => 'Cárdenas',
                    'gender' => 'Femenino',
                    'birth_date' => '2020-03-20',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Camino T-45 Runca S/N',
                    'commune' => 'Máfil',
                    'phone' => '974304634',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.172.860-3',
                    'first_name' => 'Sofia Victoria',
                    'last_name_father' => 'Caifil',
                    'last_name_mother' => 'Guzmán',
                    'gender' => 'Femenino',
                    'birth_date' => '2020-01-24',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Rinconada S/N',
                    'commune' => 'Máfil',
                    'phone' => '978373943',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '28.667.251-5',
                    'first_name' => 'Liam Abel',
                    'last_name_father' => 'Conde',
                    'last_name_mother' => 'Ayaviri',
                    'gender' => 'Masculino',
                    'birth_date' => '2019-12-20',
                    'nationality' => 'Boliviana',
                    'religion' => 'Ninguna',
                    'address' => 'Ruta 5 Sur KM 804',
                    'commune' => 'Máfil',
                    'phone' => null,
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.032.187-9',
                    'first_name' => 'Stefano Alejandro',
                    'last_name_father' => 'Coronado',
                    'last_name_mother' => 'Lara',
                    'gender' => 'Masculino',
                    'birth_date' => '2019-10-01',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Carol Urzúa 265',
                    'commune' => 'Máfil',
                    'phone' => '961383067',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.070.203-1',
                    'first_name' => 'Cristipher Mauricio',
                    'last_name_father' => 'Coronado',
                    'last_name_mother' => 'Sepúlveda',
                    'gender' => 'Masculino',
                    'birth_date' => '2020-02-03',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa San Luis Runca N°145',
                    'commune' => 'Máfil',
                    'phone' => '995032520',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.214.133-9',
                    'first_name' => 'Angeline Elizabeth Javiera',
                    'last_name_father' => 'Cuevas',
                    'last_name_mother' => 'Wigand',
                    'gender' => 'Femenino',
                    'birth_date' => '2020-02-21',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Runca S/N Kilómetro 5',
                    'commune' => 'Máfil',
                    'phone' => '991405104',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],

                // 11 a 22 (continúan pero ESCRITOS)
                [
                    'rut' => '27.001.498-4',
                    'first_name' => 'Isabella Trinidad',
                    'last_name_father' => 'Durán',
                    'last_name_mother' => 'Sáez',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-08-16',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Las Lomas S/N',
                    'commune' => 'Máfil',
                    'phone' => '926052215',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.877.391-6',
                    'first_name' => 'Arturo André',
                    'last_name_father' => 'Flández',
                    'last_name_mother' => 'Tripailaf',
                    'gender' => 'Masculino',
                    'birth_date' => '2019-06-16',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Río Máfil 324',
                    'commune' => 'Máfil',
                    'phone' => null,
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.839.337-4',
                    'first_name' => 'Emilia Antonia',
                    'last_name_father' => 'Mansilla',
                    'last_name_mother' => 'Pinto',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-05-16',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Folilco S/N',
                    'commune' => 'Máfil',
                    'phone' => '975435691',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.095.990-3',
                    'first_name' => 'Santiago Alonso',
                    'last_name_father' => 'Medina',
                    'last_name_mother' => 'Sepúlveda',
                    'gender' => 'Masculino',
                    'birth_date' => '2019-11-25',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Av. Arturo Prat 255',
                    'commune' => 'Máfil',
                    'phone' => '961565599',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.887.175-7',
                    'first_name' => 'Germán Matías',
                    'last_name_father' => 'Molina',
                    'last_name_mother' => 'Baeza',
                    'gender' => 'Masculino',
                    'birth_date' => '2019-06-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Folilco S/N',
                    'commune' => 'Máfil',
                    'phone' => '934605645',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.149.470-k',
                    'first_name' => 'Reymundo Leonel',
                    'last_name_father' => 'Morales',
                    'last_name_mother' => 'Zurita',
                    'gender' => 'Masculino',
                    'birth_date' => '2020-01-02',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Darío Salas 739',
                    'commune' => 'Máfil',
                    'phone' => '987208473',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.110.471-5',
                    'first_name' => 'Isidora Belén',
                    'last_name_father' => 'Pérez',
                    'last_name_mother' => 'Barriga',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-12-02',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Las Lomas Fundo Brasil S/N',
                    'commune' => 'Máfil',
                    'phone' => '926404261',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.181.205-1',
                    'first_name' => 'Máximo Leonardo Gabriel',
                    'last_name_father' => 'Sandoval',
                    'last_name_mother' => 'Velásquez',
                    'gender' => 'Masculino',
                    'birth_date' => '2020-01-23',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Fundo Monte Verde S/N',
                    'commune' => 'Máfil',
                    'phone' => '990956325',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.776.493-k',
                    'first_name' => 'Ian Alexander',
                    'last_name_father' => 'Sanhueza',
                    'last_name_mother' => 'Garrido',
                    'gender' => 'Masculino',
                    'birth_date' => '2019-04-02',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Guillermo Hartl 157',
                    'commune' => 'Máfil',
                    'phone' => '965566423',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.210.761-0',
                    'first_name' => 'Isabella Ainhoa',
                    'last_name_father' => 'Utreras',
                    'last_name_mother' => 'Pichipil',
                    'gender' => 'Femenino',
                    'birth_date' => '2020-02-13',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Rinconada #4',
                    'commune' => 'Máfil',
                    'phone' => '932199811',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '27.102.807-5',
                    'first_name' => 'Monserrat Andrea',
                    'last_name_father' => 'Villagra',
                    'last_name_mother' => 'Leal',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-11-28',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Sector San Pedro',
                    'commune' => 'Máfil',
                    'phone' => '940705888',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.781.809-6',
                    'first_name' => 'Emilia Antonella Ignacia',
                    'last_name_father' => 'Ruiz',
                    'last_name_mother' => 'Contreras',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-04-05',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Putreguel S/N',
                    'commune' => 'Máfil',
                    'phone' => '975373067',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
            ];

            foreach ($students as $s) {

                $student = Student::firstOrCreate(
                    ['rut' => strtolower($s['rut'])],
                    [
                        'first_name' => $s['first_name'],
                        'last_name_father' => $s['last_name_father'],
                        'last_name_mother' => $s['last_name_mother'],
                        'gender' => $s['gender'],
                        'birth_date' => $s['birth_date'],
                        'nationality' => $s['nationality'],
                        'religion' => $s['religion'],
                        'address' => $s['address'],
                        'commune' => $s['commune'],
                        'phone' => $s['phone'],
                        'indigenous_ancestry' => !empty($s['indigenous']),
                        'indigenous_ancestry_type' => $s['indigenous'],
                    ]
                );

                Enrollment::firstOrCreate(
                    [
                        'student_id' => $student->id,
                        'school_year' => 2026,
                    ],
                    [
                        'course_id' => $course->id,
                        'enrollment_type' => 'Returning Student',
                        'status' => 'Pending',
                        'has_health_issues' => $s['health'],
                        'is_pie_student' => $s['pie'],
                    ]
                );
            }
        });
    }
}
