<?php

namespace Database\Seeders\Legacy;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Student;
use App\Models\Enrollment;
use App\Models\Course;

class OctavoBasicoA2025Seeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            // Curso 8° Básico A – año escolar 2026
            $course = Course::whereHas('gradeLevel', function ($q) {
                    $q->where('name', '8° Básico');
                })
                ->where('letter', 'A')
                ->where('school_year', 2026)
                ->firstOrFail();

            $students = [

                /* =====================================================
                 * BLOQUE 1 (1–17)
                 * ===================================================== */

                [
                    'rut' => '23.998.580-7',
                    'first_name' => 'Vicente Alonso',
                    'last_name_father' => 'Elos',
                    'last_name_mother' => 'Beroiza',
                    'gender' => 'Masculino',
                    'birth_date' => '2012-06-29',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Fundo Los Pellines, Los Laureles, Mulpun',
                    'commune' => 'Máfil',
                    'phone' => '993403725',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.050.201-1',
                    'first_name' => 'Ángel Giovanni',
                    'last_name_father' => 'Rehl',
                    'last_name_mother' => 'Guevia',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-05-26',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Sector Nilhue',
                    'commune' => 'Máfil',
                    'phone' => '968546012',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => true,
                ],
                [
                    'rut' => '23.417.544-0',
                    'first_name' => 'Catalina Sofía',
                    'last_name_father' => 'Saez',
                    'last_name_mother' => 'Gutiérrez',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-09-07',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'León Montecinos 245',
                    'commune' => 'Máfil',
                    'phone' => '936658723',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.766.477-0',
                    'first_name' => 'Yaliban Yajaira',
                    'last_name_father' => 'Acuña',
                    'last_name_mother' => 'Vargas',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-06-28',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Villa Las Palmeras, Calle Norte 191',
                    'commune' => 'Máfil',
                    'phone' => '940806298',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.881.488-k',
                    'first_name' => 'Milhem Andrés',
                    'last_name_father' => 'Aleuy',
                    'last_name_mother' => 'Vargas',
                    'gender' => 'Masculino',
                    'birth_date' => '2012-02-24',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Villa Entre Ríos, Río Máfil 328',
                    'commune' => 'Máfil',
                    'phone' => '982275865',
                    'indigenous' => true,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.726.851-2',
                    'first_name' => 'Victoria Catalina',
                    'last_name_father' => 'Bravo',
                    'last_name_mother' => 'Donoso',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-08-24',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Población Alabama, Tte. Merino 22',
                    'commune' => 'Máfil',
                    'phone' => '996437125',
                    'indigenous' => true,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.724.719-1',
                    'first_name' => 'Darli Ailin',
                    'last_name_father' => 'Bravo',
                    'last_name_mother' => 'Troncoso',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-08-19',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa Los Castaños, Psje. Oscar Quiroz Jara 152',
                    'commune' => 'Máfil',
                    'phone' => '976021293',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.816.789-2',
                    'first_name' => 'Martina Ignacia',
                    'last_name_father' => 'Caro',
                    'last_name_mother' => 'Campos',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-12-07',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'O’Higgins 474, Santa Laura',
                    'commune' => 'Máfil',
                    'phone' => '954178614',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.898.819-5',
                    'first_name' => 'Sofía Esperanza',
                    'last_name_father' => 'Carrasco',
                    'last_name_mother' => 'López',
                    'gender' => 'Femenino',
                    'birth_date' => '2012-01-08',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Linguento S/N',
                    'commune' => 'Máfil',
                    'phone' => '953920155',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.689.634-k',
                    'first_name' => 'Carla Katalina',
                    'last_name_father' => 'Carrasco',
                    'last_name_mother' => 'Moris',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-07-09',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Fundo San Carlos, Peña Flor',
                    'commune' => 'Máfil',
                    'phone' => '94865137',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.738.330-3',
                    'first_name' => 'Alex Eduardo',
                    'last_name_father' => 'Cartes',
                    'last_name_mother' => 'Triviño',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-09-06',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Calle Servicio 79',
                    'commune' => 'Máfil',
                    'phone' => '944290361',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.955.944-1',
                    'first_name' => 'Monserrat Valeria',
                    'last_name_father' => 'Díaz',
                    'last_name_mother' => 'Labrín',
                    'gender' => 'Femenino',
                    'birth_date' => '2012-05-21',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Monte Grande 34, Villa Porvenir',
                    'commune' => 'Máfil',
                    'phone' => '981867976',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '22.841.159-0',
                    'first_name' => 'Brayan Alexander',
                    'last_name_father' => 'Durán',
                    'last_name_mother' => 'Saez',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-10-08',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Fundo Las Lomas S/N',
                    'commune' => 'Máfil',
                    'phone' => '926052215',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.559.267-3',
                    'first_name' => 'Miguel Ángel Hernando',
                    'last_name_father' => 'Durán',
                    'last_name_mother' => 'Saez',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-02-08',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Fundo Las Lomas S/N',
                    'commune' => 'Máfil',
                    'phone' => '953549328',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.398.380-7',
                    'first_name' => 'Mariangel Jhoselin',
                    'last_name_father' => 'Galvis',
                    'last_name_mother' => 'Orellan',
                    'gender' => 'Femenino',
                    'birth_date' => '2012-04-13',
                    'nationality' => 'Venezolana',
                    'religion' => 'Otra',
                    'address' => 'Santa Rosa Norte S/N, San José de la Mariquina',
                    'commune' => 'Mariquina',
                    'phone' => '979143765',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.687.347-1',
                    'first_name' => 'Sergio Sebastián',
                    'last_name_father' => 'Gonzales',
                    'last_name_mother' => 'Guzmán',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-07-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Rinconada S/N',
                    'commune' => 'Máfil',
                    'phone' => '978373943',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.790.834-1',
                    'first_name' => 'Cristóbal de León',
                    'last_name_father' => 'Gutiérrez',
                    'last_name_mother' => 'Garrios',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-10-30',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Parcela 12, Cudico',
                    'commune' => 'Máfil',
                    'phone' => '951744643',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],

                /* =====================================================
                 * BLOQUE 2 (18–33)
                 * ===================================================== */

                [
                    'rut' => '23.911.706-6',
                    'first_name' => 'Joaquín Elías',
                    'last_name_father' => 'Lagos',
                    'last_name_mother' => 'Ojeda',
                    'gender' => 'Masculino',
                    'birth_date' => '2012-04-01',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Mulpun S/N',
                    'commune' => 'Máfil',
                    'phone' => '975716191',
                    'indigenous' => true,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '23.843.802-0',
                    'first_name' => 'Dylan Ignacio',
                    'last_name_father' => 'León',
                    'last_name_mother' => 'Miranda',
                    'gender' => 'Masculino',
                    'birth_date' => '2012-01-11',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Putreguel S/N',
                    'commune' => 'Máfil',
                    'phone' => '963130002',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.708.088-2',
                    'first_name' => 'Valentina Magdalena',
                    'last_name_father' => 'Lovera',
                    'last_name_mother' => 'Fuentealba',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-07-30',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Hullicoihue',
                    'commune' => 'Máfil',
                    'phone' => '975886844',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.808.072-k',
                    'first_name' => 'Lisseth Soledad',
                    'last_name_father' => 'Marquez',
                    'last_name_mother' => 'Riquelme',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-11-14',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Los Castaños',
                    'commune' => 'Máfil',
                    'phone' => '939051509',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.199.722-9',
                    'first_name' => 'Guillermo Antonio',
                    'last_name_father' => 'Moraga',
                    'last_name_mother' => 'Mora',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-11-22',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Los Castaños, Jaime Vera 199',
                    'commune' => 'Máfil',
                    'phone' => null,
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.779.963-1',
                    'first_name' => 'Guillermo Alonso',
                    'last_name_father' => 'Morales',
                    'last_name_mother' => 'Espinoza',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-10-24',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Iñaque S/N',
                    'commune' => 'Máfil',
                    'phone' => '993281560',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '23.666.326-4',
                    'first_name' => 'Gabriel Ignacio',
                    'last_name_father' => 'Morales',
                    'last_name_mother' => 'Lara',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-06-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Villa Entre Ríos, Psje. Nonoco 233',
                    'commune' => 'Máfil',
                    'phone' => '999726837',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.762.860-8',
                    'first_name' => 'Genesis Katerine',
                    'last_name_father' => 'Moris',
                    'last_name_mother' => 'Soto',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-09-30',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Fundo Putabla S/N',
                    'commune' => 'Máfil',
                    'phone' => '934314086',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.838.129-0',
                    'first_name' => 'Edison Cristóbal',
                    'last_name_father' => 'Olivia',
                    'last_name_mother' => 'Araus',
                    'gender' => 'Masculino',
                    'birth_date' => '2012-01-05',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Ciruelos, Los Olmos 84',
                    'commune' => 'Máfil',
                    'phone' => '962161814',
                    'indigenous' => true,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.741.995-2',
                    'first_name' => 'Eniyer Amaral',
                    'last_name_father' => 'Rebolledo',
                    'last_name_mother' => 'Ruiz',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-09-01',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Población Padre Hurtado 328',
                    'commune' => 'Máfil',
                    'phone' => '941680323',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.784.330-4',
                    'first_name' => 'Alejandra Nicolett',
                    'last_name_father' => 'Recabal',
                    'last_name_mother' => 'Peña',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-10-27',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Pedro de Valdivia 10 Interior',
                    'commune' => 'Máfil',
                    'phone' => '954534924',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.515.893-0',
                    'first_name' => 'Abigail Estela',
                    'last_name_father' => 'Salgado',
                    'last_name_mother' => 'Fernández',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-12-24',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Sector Llastuco S/N',
                    'commune' => 'Máfil',
                    'phone' => '945557169',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.889.498-0',
                    'first_name' => 'Rafael Ignacio',
                    'last_name_father' => 'Sepúlveda',
                    'last_name_mother' => 'Pinilla',
                    'gender' => 'Masculino',
                    'birth_date' => '2012-03-05',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Carol Urzúa Interior S/N',
                    'commune' => 'Máfil',
                    'phone' => '992613881',
                    'indigenous' => true,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.896.815-1',
                    'first_name' => 'Isidora Ignacia',
                    'last_name_father' => 'Trujillo',
                    'last_name_mother' => 'Muñoz',
                    'gender' => 'Femenino',
                    'birth_date' => '2012-03-12',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Calle Río Iñaque 249, Villa Entre Ríos',
                    'commune' => 'Máfil',
                    'phone' => '934314086',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '23.872.424-4',
                    'first_name' => 'Juan Alejandro',
                    'last_name_father' => 'Itachy',
                    'last_name_mother' => 'Barriga Cabrera',
                    'gender' => 'Masculino',
                    'birth_date' => '2012-02-12',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Linguento S/N',
                    'commune' => 'Máfil',
                    'phone' => '965556218',
                    'indigenous' => true,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.656.727-3',
                    'first_name' => 'Jostin Ariel',
                    'last_name_father' => 'Flandez',
                    'last_name_mother' => 'Carrillo',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-05-20',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Molco S/N',
                    'commune' => 'Máfil',
                    'phone' => '941859421',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
            ];

            foreach ($students as $s) {

                $student = Student::firstOrCreate(
                    ['rut' => strtolower($s['rut'])],
                    [
                        'first_name' => $s['first_name'],
                        'last_name_father' => $s['last_name_father'],
                        'last_name_mother' => $s['last_name_mother'],
                        'gender' => $s['gender'],
                        'birth_date' => $s['birth_date'],
                        'nationality' => $s['nationality'],
                        'religion' => $s['religion'],
                        'address' => $s['address'],
                        'commune' => $s['commune'],
                        'phone' => $s['phone'],
                        'indigenous_ancestry' => !empty($s['indigenous']),
                        'indigenous_ancestry_type' => $s['indigenous'],
                        'has_health_issues' => $s['health'],
                    ]
                );

                Enrollment::firstOrCreate(
                    [
                        'student_id' => $student->id,
                        'school_year' => 2026,
                    ],
                    [
                        'course_id' => $course->id,
                        'enrollment_type' => 'Returning Student',
                        'status' => 'Pending',
                        'has_health_issues' => $s['health'],
                        'is_pie_student' => $s['pie'],
                    ]
                );
            }
        });
    }
}
