<?php

namespace Database\Seeders\Legacy;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Student;
use App\Models\Enrollment;
use App\Models\Course;

class PrimeroBasico2025Seeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            $course = Course::whereHas('gradeLevel', fn ($q) =>
                $q->where('name', '1° Básico')
            )->where('school_year', 2026)->firstOrFail();

            $students = [

                [
                    'rut' => '26.269.417-8',
                    'first_name' => 'Melek Anais',
                    'last_name_father' => 'Alvarez',
                    'last_name_mother' => 'Mena',
                    'gender' => 'Femenino',
                    'birth_date' => '2018-05-11',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Runca S/N',
                    'commune' => 'Máfil',
                    'phone' => '942642225',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '26.351.495-5',
                    'first_name' => 'Guisel Aylin',
                    'last_name_father' => 'Abarca',
                    'last_name_mother' => 'Peña',
                    'gender' => 'Femenino',
                    'birth_date' => '2018-06-23',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Runca S/N',
                    'commune' => 'Máfil',
                    'phone' => '942563004',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.649.061-5',
                    'first_name' => 'Noah Benjamin',
                    'last_name_father' => 'Abarca',
                    'last_name_mother' => 'Sarabia',
                    'gender' => 'Masculino',
                    'birth_date' => '2019-01-09',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Linguiento',
                    'commune' => 'Máfil',
                    'phone' => '994198736',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.590.543-9',
                    'first_name' => 'Guissellle Danhae',
                    'last_name_father' => 'Berrocal',
                    'last_name_mother' => 'Andrade',
                    'gender' => 'Masculino',
                    'birth_date' => '2018-11-24',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Pedro Aguirre 260',
                    'commune' => 'Máfil',
                    'phone' => '966592446',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.605.238-3',
                    'first_name' => 'Lucas Ignacio',
                    'last_name_father' => 'Cares',
                    'last_name_mother' => 'Alvarado',
                    'gender' => 'Masculino',
                    'birth_date' => '2018-12-05',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Blanco Encalada S/N',
                    'commune' => 'Máfil',
                    'phone' => '979131387',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.339.222-1',
                    'first_name' => 'Mateo Simón',
                    'last_name_father' => 'Flández',
                    'last_name_mother' => 'Briones',
                    'gender' => 'Masculino',
                    'birth_date' => '2018-06-22',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Germán Fehlandt #79',
                    'commune' => 'Máfil',
                    'phone' => '964979911',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '26.290.516-0',
                    'first_name' => 'Catalina de los Ángeles',
                    'last_name_father' => 'Gálvez',
                    'last_name_mother' => 'Garrido',
                    'gender' => 'Femenino',
                    'birth_date' => '2018-05-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector Los Águilas Parcela 8',
                    'commune' => 'Máfil',
                    'phone' => '920278183',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.440.315-4',
                    'first_name' => 'Renata Inés',
                    'last_name_father' => 'Lagos',
                    'last_name_mother' => 'Reyes',
                    'gender' => 'Masculino',
                    'birth_date' => '2018-08-24',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Villa Los Castaños #61',
                    'commune' => 'Máfil',
                    'phone' => '995281089',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.305.903-4',
                    'first_name' => 'Nicolás Liam',
                    'last_name_father' => 'Martínez',
                    'last_name_mother' => 'Vera',
                    'gender' => 'Masculino',
                    'birth_date' => '2018-05-27',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector Los Águilas S/N',
                    'commune' => 'Máfil',
                    'phone' => '926209116',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '26.313.944-5',
                    'first_name' => 'Yuliana',
                    'last_name_father' => 'Matus',
                    'last_name_mother' => 'Muñoz',
                    'gender' => 'Femenino',
                    'birth_date' => '2018-06-08',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'La Traca 404',
                    'commune' => 'Máfil',
                    'phone' => '983896220',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.638.251-0',
                    'first_name' => 'Santiago Vicente',
                    'last_name_father' => 'Muñoz',
                    'last_name_mother' => 'Montes',
                    'gender' => 'Masculino',
                    'birth_date' => '2019-01-03',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Iñaque',
                    'commune' => 'Máfil',
                    'phone' => '989335729',
                    'indigenous' => 'Mapuche',
                    'health' => true,
                    'pie' => true,
                ],
                [
                    'rut' => '26.373.571-4',
                    'first_name' => 'Benjamín Isaías',
                    'last_name_father' => 'Ortiz',
                    'last_name_mother' => 'Campos',
                    'gender' => 'Masculino',
                    'birth_date' => '2018-07-17',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Fundo Molco',
                    'commune' => 'Máfil',
                    'phone' => '967012949',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.255.362-0',
                    'first_name' => 'Matías Esteban',
                    'last_name_father' => 'Ortiz',
                    'last_name_mother' => 'Matus',
                    'gender' => 'Masculino',
                    'birth_date' => '2018-05-03',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Palo Santo 389',
                    'commune' => 'Máfil',
                    'phone' => '974475260',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.362.313-4',
                    'first_name' => 'Berluscronita Pierre',
                    'last_name_father' => 'Jean',
                    'last_name_mother' => null,
                    'gender' => 'Femenino',
                    'birth_date' => '2018-06-30',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Runca',
                    'commune' => 'Máfil',
                    'phone' => '979973025',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => true,
                ],
                [
                    'rut' => '26.665.366-2',
                    'first_name' => 'Pascual Efraín',
                    'last_name_father' => 'Patiño',
                    'last_name_mother' => 'Cordovez',
                    'gender' => 'Masculino',
                    'birth_date' => '2019-01-21',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Huillón S/N',
                    'commune' => 'Máfil',
                    'phone' => '931041460',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '26.659.954-4',
                    'first_name' => 'Emily Anahis',
                    'last_name_father' => 'Pinilla',
                    'last_name_mother' => 'Silva',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-01-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Runca Villa San Luis Pasaje Los Copihues #113',
                    'commune' => 'Máfil',
                    'phone' => '942914041',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.284.363-7',
                    'first_name' => 'Joaquín Ignacio',
                    'last_name_father' => 'Santana',
                    'last_name_mother' => 'Aedo',
                    'gender' => 'Masculino',
                    'birth_date' => '2018-05-23',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Runca Laguna Los Patos',
                    'commune' => 'Máfil',
                    'phone' => '982745621',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.251.271-1',
                    'first_name' => 'Gael Mateo',
                    'last_name_father' => 'Valladares',
                    'last_name_mother' => 'Hidalgo',
                    'gender' => 'Masculino',
                    'birth_date' => '2018-04-29',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Mulpun Fundo La Victoria',
                    'commune' => 'Máfil',
                    'phone' => '953123518',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.761.000-2',
                    'first_name' => 'Emilit Antonella',
                    'last_name_father' => 'Tapia',
                    'last_name_mother' => 'Catalán',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-03-22',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Blanco Encalada #183',
                    'commune' => 'Máfil',
                    'phone' => '928186217',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.422.607-5',
                    'first_name' => 'Ayalen Suyai',
                    'last_name_father' => 'Velázquez',
                    'last_name_mother' => 'Antio',
                    'gender' => 'Femenino',
                    'birth_date' => '2019-02-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Mulpun Comunidad',
                    'commune' => 'Máfil',
                    'phone' => '959012973',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => true,
                ],
            ];

            foreach ($students as $s) {

                $student = Student::firstOrCreate(
                    ['rut' => strtolower($s['rut'])],
                    [
                        'first_name' => $s['first_name'],
                        'last_name_father' => $s['last_name_father'],
                        'last_name_mother' => $s['last_name_mother'],
                        'gender' => $s['gender'],
                        'birth_date' => $s['birth_date'],
                        'nationality' => $s['nationality'],
                        'religion' => $s['religion'],
                        'address' => $s['address'],
                        'commune' => $s['commune'],
                        'phone' => $s['phone'],
                        'indigenous_ancestry' => !empty($s['indigenous']),
                        'indigenous_ancestry_type' => $s['indigenous'],
                    ]
                );

                Enrollment::firstOrCreate(
                    [
                        'student_id' => $student->id,
                        'school_year' => 2026,
                    ],
                    [
                        'course_id' => $course->id,
                        'enrollment_type' => 'Returning Student',
                        'status' => 'Pending',
                        'has_health_issues' => $s['health'],
                        'is_pie_student' => $s['pie'],
                    ]
                );
            }
        });
    }
}
