<?php

namespace Database\Seeders\Legacy;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Student;
use App\Models\Enrollment;
use App\Models\Course;

class PrimeroMedioA2025Seeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            // Curso 1° Medio A – matrícula 2026 (estado Pending)
            $course = Course::whereHas('gradeLevel', function ($q) {
                $q->where('name', '1° Medio');
            })
                ->where('letter', 'A')
                ->where('school_year', 2026)
                ->firstOrFail();

            $students = [

                /* =====================================================
                 * BLOQUE 1 (1–15)
                 * ===================================================== */

                [
                    'rut' => '23.488.982-6',
                    'first_name' => 'Nicolás Ignacio',
                    'last_name_father' => 'Montoña',
                    'last_name_mother' => 'Fariña',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-11-23',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Camino Huillón S/N',
                    'commune' => 'Máfil',
                    'phone' => '921632077',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '100.822.015-4',
                    'first_name' => 'Wilda',
                    'last_name_father' => 'Delva',
                    'last_name_mother' => null,
                    'gender' => 'Femenino',
                    'birth_date' => '2010-08-05',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Fundo Los Maitenes S/N',
                    'commune' => 'Máfil',
                    'phone' => '937408574',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.564.093-7',
                    'first_name' => 'Milca Dynara',
                    'last_name_father' => 'Ortiz',
                    'last_name_mother' => 'Huenchullanca',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-02-18',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Fundo Molco',
                    'commune' => 'Máfil',
                    'phone' => '93297524',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.470.381-1',
                    'first_name' => 'Benjamín Alexander',
                    'last_name_father' => 'Álvarez',
                    'last_name_mother' => 'Castillo',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-11-04',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Bernardo O’Higgins 378',
                    'commune' => 'Máfil',
                    'phone' => '95672347',
                    'indigenous' => 'Sin especificar',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.424.862-6',
                    'first_name' => 'Benjamín Alejandro',
                    'last_name_father' => 'Chuñil',
                    'last_name_mother' => 'Briones',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-07-01',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Germán Fehlandt #83, Máfil',
                    'commune' => 'Máfil',
                    'phone' => '64207943',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.473.265-k', // normalizado desde "23473265-k"
                    'first_name' => 'María Paz',
                    'last_name_father' => 'Córdova',
                    'last_name_mother' => null,
                    'gender' => 'Femenino',
                    'birth_date' => null, // "39-10-2010" no es corregible con certeza
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector La Traca - Camino Folilco, Máfil',
                    'commune' => 'Máfil',
                    'phone' => '956422638',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.705.774-0',
                    'first_name' => 'Estefanía Odhet',
                    'last_name_father' => 'Delgado',
                    'last_name_mother' => 'Cisterna',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-07-27',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Arturo Prat S/N, Máfil',
                    'commune' => 'Máfil',
                    'phone' => '99855808',
                    'indigenous' => 'Sin especificar',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.350.543-9',
                    'first_name' => 'Fabián Alexis',
                    'last_name_father' => 'Duarte',
                    'last_name_mother' => 'Garrios',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-06-15',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Parcela 12, Iñaque',
                    'commune' => 'Máfil',
                    'phone' => '94678635',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.322.716-1',
                    'first_name' => 'Ignacia Yarela',
                    'last_name_father' => 'Escobar',
                    'last_name_mother' => 'Cañoles',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-04-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Pasaje Elqui 68, Máfil',
                    'commune' => 'Máfil',
                    'phone' => '955144769',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.391.246-3',
                    'first_name' => 'Vicente Ezequiel',
                    'last_name_father' => 'Farías',
                    'last_name_mother' => 'Zuñiga',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-08-09',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna', // venía "no apta"
                    'address' => 'Pasaje Pidey S/N',
                    'commune' => 'Máfil',
                    'phone' => '976762080',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.137.953-3',
                    'first_name' => 'Vicente Andrés',
                    'last_name_father' => 'García',
                    'last_name_mother' => 'Hernández',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-10-05',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Linguento, Callejón Los Troncos 46',
                    'commune' => 'Máfil',
                    'phone' => '64214181',
                    'indigenous' => null,
                    'health' => true, // venía "si"
                    'pie' => false,
                ],
                [
                    'rut' => '23.428.686-2',
                    'first_name' => 'Anyelina Estefanía',
                    'last_name_father' => 'Garridos',
                    'last_name_mother' => 'Gonzales',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-09-19',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector Linguento, Los Troncos, Parcela 25, Máfil',
                    'commune' => 'Máfil',
                    'phone' => '959096473', // venía "9-59o96473"
                    'indigenous' => 'Sin especificar',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.372.334-7',
                    'first_name' => 'Cristofer Agustín',
                    'last_name_father' => 'Gómez',
                    'last_name_mother' => 'Cárdenas',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-07-14',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Vera Meneses Santana #38',
                    'commune' => 'Máfil',
                    'phone' => '86965525',
                    'indigenous' => 'Sin especificar',
                    'health' => false,
                    'pie' => true, // venía "si"
                ],
                [
                    'rut' => '23.459.114-2',
                    'first_name' => 'Constanza Antonia',
                    'last_name_father' => 'Guajardo',
                    'last_name_mother' => 'Peña',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-10-19',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Pedro de Valdivia Interior 10, Máfil',
                    'commune' => 'Máfil',
                    'phone' => '54534924',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.633.690-5',
                    'first_name' => 'Camila Danae',
                    'last_name_father' => 'Guzmán',
                    'last_name_mother' => 'Mera',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-04-29',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Av. Pedro de Valdivia 195',
                    'commune' => 'Máfil',
                    'phone' => '51578927',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                /* =====================================================
                 * BLOQUE 2 (16–34)
                 * ===================================================== */

                [
                    'rut' => '26.633.785-k',
                    'first_name' => 'Sofía Alejandra',
                    'last_name_father' => 'Hernández',
                    'last_name_mother' => 'Duarte',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-06-16',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'John Kennedy, Pasaje Monte Grande #1458',
                    'commune' => 'Máfil',
                    'phone' => '94474042',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.656.734-6',
                    'first_name' => 'Yessica Isidora',
                    'last_name_father' => 'Herrera',
                    'last_name_mother' => 'Chico',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-05-20',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Pedro Aguirre Cerda 145',
                    'commune' => 'Máfil',
                    'phone' => '44154660',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.268.855-6',
                    'first_name' => 'Juan Alejandro Andrés',
                    'last_name_father' => 'Jil',
                    'last_name_mother' => 'Salinas',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-03-12',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Rinconada S/N',
                    'commune' => 'Máfil',
                    'phone' => '94024107',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.446.317-9',
                    'first_name' => 'José Sebastián',
                    'last_name_father' => 'Llanquilef',
                    'last_name_mother' => 'Torres',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-10-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Hullón S/N',
                    'commune' => 'Máfil',
                    'phone' => '927067309',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.484.325-7',
                    'first_name' => 'Bastián John',
                    'last_name_father' => 'Matus',
                    'last_name_mother' => 'Navarrete',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-11-17',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Central Oriente #460',
                    'commune' => 'Máfil',
                    'phone' => '953350995',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.158.839-6',
                    'first_name' => 'Álvaro Damián',
                    'last_name_father' => 'Olavarría',
                    'last_name_mother' => 'Riquelme',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-10-24',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Samuel Altamirano 308, Villa Mafilita',
                    'commune' => 'Máfil',
                    'phone' => '951845639',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.635.875-5',
                    'first_name' => 'Javier Alonso',
                    'last_name_father' => 'Peña',
                    'last_name_mother' => 'Sandoval',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-04-21',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Sector Linguienti S/N',
                    'commune' => 'Máfil',
                    'phone' => '93998279',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.365.512-0',
                    'first_name' => 'Dayana Maricell',
                    'last_name_father' => 'Sandoval',
                    'last_name_mother' => 'Velásquez',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-06-19',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Fundo Monte Verde S/N',
                    'commune' => 'Máfil',
                    'phone' => '990955625',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.450.872-5',
                    'first_name' => 'Rafaela Antonia',
                    'last_name_father' => 'Seura',
                    'last_name_mother' => 'Chaud',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-10-15',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Putreguel',
                    'commune' => 'Máfil',
                    'phone' => '977741641',
                    'indigenous' => 'Mapuche',
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '23.473.290-0',
                    'first_name' => 'Estefany Andrea',
                    'last_name_father' => 'Soferrey',
                    'last_name_mother' => 'Baeza',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-10-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Juan Verdaguer 366, Valdivia',
                    'commune' => 'Máfil',
                    'phone' => '965719495',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.508.697-2',
                    'first_name' => 'Nicolás Alfonso',
                    'last_name_father' => 'Stolzenbach',
                    'last_name_mother' => 'Mondaca',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-12-23',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Chancoyán Alto S/N',
                    'commune' => 'Máfil',
                    'phone' => '957809025',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.606.353-4',
                    'first_name' => 'Jesús Alejandro',
                    'last_name_father' => 'Subiabre',
                    'last_name_mother' => 'Pinto',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-03-19',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Fundo Los Maitenes S/N',
                    'commune' => 'Máfil',
                    'phone' => '940750532',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.427.882-7',
                    'first_name' => 'Macarena Ignacia',
                    'last_name_father' => 'Tapia',
                    'last_name_mother' => 'Gallegos',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-09-16',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Fundo Santa Elena S/N',
                    'commune' => 'Máfil',
                    'phone' => '975415425',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.341.753-k',
                    'first_name' => 'Benjamín José',
                    'last_name_father' => 'Trujillo',
                    'last_name_mother' => 'Bravo',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-06-04',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Darío Salas 865, Población Libertad',
                    'commune' => 'Máfil',
                    'phone' => '933592053',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.107.524-0',
                    'first_name' => 'María José',
                    'last_name_father' => 'Velásquez',
                    'last_name_mother' => 'Loncochino',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-08-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Fundo Las Quemas',
                    'commune' => 'Máfil',
                    'phone' => '944003261',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.134.772-0',
                    'first_name' => 'Cristopher Iván',
                    'last_name_father' => 'Albornoz',
                    'last_name_mother' => 'Paillan',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-09-27',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Rinconada S/N',
                    'commune' => 'Máfil',
                    'phone' => '926366395',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.498.895-6',
                    'first_name' => 'Javiera Annelie',
                    'last_name_father' => 'Osorio',
                    'last_name_mother' => 'Moraga',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-12-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Linguiento, Runca Los Troncos N°43',
                    'commune' => 'Máfil',
                    'phone' => '926997620',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.466.172-8',
                    'first_name' => 'Johan Mauricio',
                    'last_name_father' => 'Paredes',
                    'last_name_mother' => 'Martin',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-10-29',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'San Pedro S/N',
                    'commune' => 'Máfil',
                    'phone' => '944207992',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.396.806-4',
                    'first_name' => 'Alejandra Soledad',
                    'last_name_father' => 'Bastías',
                    'last_name_mother' => 'Martínez',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-08-09',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Las Parcelas, Camino a Riñihue S/N',
                    'commune' => 'Máfil',
                    'phone' => '965720839',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
            ];

            foreach ($students as $s) {

                $student = Student::firstOrCreate(
                    ['rut' => strtolower($s['rut'])],
                    [
                        'first_name' => $s['first_name'],
                        'last_name_father' => $s['last_name_father'],
                        'last_name_mother' => $s['last_name_mother'],
                        'gender' => $s['gender'],
                        'birth_date' => $s['birth_date'],
                        'nationality' => $s['nationality'],
                        'religion' => $s['religion'],
                        'address' => $s['address'],
                        'commune' => $s['commune'],
                        'phone' => $s['phone'],
                        'indigenous_ancestry' => !empty($s['indigenous']),
                        'indigenous_ancestry_type' => $s['indigenous'],
                        'has_health_issues' => $s['health'],
                    ]
                );

                Enrollment::firstOrCreate(
                    [
                        'student_id' => $student->id,
                        'school_year' => 2026,
                    ],
                    [
                        'course_id' => $course->id,
                        'enrollment_type' => 'Returning Student',
                        'status' => 'Pending',
                        'has_health_issues' => $s['health'],
                        'is_pie_student' => $s['pie'],
                    ]
                );
            }
        });
    }
}
