<?php

namespace Database\Seeders\Legacy;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Student;
use App\Models\Enrollment;
use App\Models\Course;

class PrimeroMedioB2025Seeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            // Curso 1° Medio B – matrícula 2026 (estado Pending)
            $course = Course::whereHas('gradeLevel', function ($q) {
                $q->where('name', '1° Medio');
            })
                ->where('letter', 'B')
                ->where('school_year', 2026)
                ->firstOrFail();

            $students = [

                /* =====================================================
                 * BLOQUE 1 (1–14)
                 * ===================================================== */

                [
                    'rut' => '23.379.990-4',
                    'first_name' => 'Paloma Andrea',
                    'last_name_father' => 'Cid',
                    'last_name_mother' => 'Chávez',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-07-21',
                    'nationality' => 'Chilena',
                    'religion' => 'Otra', // venía "si"
                    'address' => 'Avenida Prat 350',
                    'commune' => 'Máfil',
                    'phone' => '989235427',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.618.823-1',
                    'first_name' => 'Martín Alejandro',
                    'last_name_father' => 'Garnica',
                    'last_name_mother' => 'Matus',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-01-21',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Calle Los Alerces',
                    'commune' => 'Máfil',
                    'phone' => '958869950',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.945.640-7',
                    'first_name' => 'Aarón Emilio',
                    'last_name_father' => 'Álvarez',
                    'last_name_mother' => 'Araya',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-02-08',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Los Alerces 52',
                    'commune' => 'Máfil',
                    'phone' => '989899575',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.432.576-0',
                    'first_name' => 'Danae Antonela',
                    'last_name_father' => 'Marín',
                    'last_name_mother' => 'Saravia',
                    'gender' => 'Masculino', // según ficha original
                    'birth_date' => '2010-09-22',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Folilco Las Alturas',
                    'commune' => 'Máfil',
                    'phone' => '987972118',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.073.260-4',
                    'first_name' => 'Estefanía Constanza',
                    'last_name_father' => 'Alvear',
                    'last_name_mother' => 'Silva',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-07-14',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Lingüento',
                    'commune' => 'Máfil',
                    'phone' => '969189055',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.462.975-3',
                    'first_name' => 'Catalina Belén',
                    'last_name_father' => 'Reyes',
                    'last_name_mother' => 'Contreras',
                    'gender' => 'Femenino',
                    'birth_date' => '2007-06-04',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'La Traca Interior 189',
                    'commune' => 'Máfil',
                    'phone' => '958875285',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.430.523-9',
                    'first_name' => 'David Ignacio',
                    'last_name_father' => 'Acuña',
                    'last_name_mother' => 'Montecinos',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-09-15',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Llastuco',
                    'commune' => 'Máfil',
                    'phone' => '96618173',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.290.791-6',
                    'first_name' => 'Yadira Omara',
                    'last_name_father' => 'Aleuy',
                    'last_name_mother' => 'Vargas',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-04-05',
                    'nationality' => 'Chilena',
                    'religion' => 'Otra', // venía "si"
                    'address' => 'Villa Entre Ríos',
                    'commune' => 'Máfil',
                    'phone' => '982275865',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.577.127-6',
                    'first_name' => 'Bárbara Agustina',
                    'last_name_father' => 'Campos',
                    'last_name_mother' => 'Flández',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-03-05',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Villa Los Castaños N°240',
                    'commune' => 'Máfil',
                    'phone' => '942319945',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.225.781-4',
                    'first_name' => 'José Ignacio',
                    'last_name_father' => 'Carrasco',
                    'last_name_mother' => 'López',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-02-08',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Lingüento S/N',
                    'commune' => 'Máfil',
                    'phone' => '98582547',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.626.679-6',
                    'first_name' => 'Javiera Belén',
                    'last_name_father' => 'Cárdenas',
                    'last_name_mother' => 'Gomes',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-04-21',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Arturo Prat 222',
                    'commune' => 'Máfil',
                    'phone' => '932747759',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.803.181-1', // normalizado desde fila sin RUT válido
                    'first_name' => 'Camila Antonia',
                    'last_name_father' => 'Cofré',
                    'last_name_mother' => 'Moris',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-03-18',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Fundo Peña Flor',
                    'commune' => 'Máfil',
                    'phone' => '971954889',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.803.964-0',
                    'first_name' => 'Antonia Millaleth',
                    'last_name_father' => 'Coronado',
                    'last_name_mother' => 'Ramírez',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-08-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Yastuco N°4',
                    'commune' => 'Máfil',
                    'phone' => '948617718',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.520.189-5',
                    'first_name' => 'Amanda Julieta',
                    'last_name_father' => 'Cumín',
                    'last_name_mother' => 'Meléndez',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-12-31',
                    'nationality' => 'Chilena',
                    'religion' => 'Otra', // Testigo de Jehová
                    'address' => 'Piday S/N',
                    'commune' => 'Máfil',
                    'phone' => '999484047',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.028.517-7',
                    'first_name' => 'José Octavio',
                    'last_name_father' => 'Ganga',
                    'last_name_mother' => 'Tabia',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-04-13',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Pedro de Valdivia #404',
                    'commune' => 'Máfil',
                    'phone' => '923914003',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.556.545-5',
                    'first_name' => 'Vicente Javier',
                    'last_name_father' => 'Gomes',
                    'last_name_mother' => 'Lopez',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-02-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Chancoyan',
                    'commune' => 'Valdivia',
                    'phone' => '956172768',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.531.516-5',
                    'first_name' => 'Alberrth Benjamin',
                    'last_name_father' => 'Atus',
                    'last_name_mother' => 'Contreras',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-01-03',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa Mafilita',
                    'commune' => 'Máfil',
                    'phone' => '995175902',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.202.338-4',
                    'first_name' => 'Cristofer Alexander',
                    'last_name_father' => 'Norabuena',
                    'last_name_mother' => 'Cañoles',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-12-12',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Pelchuquin',
                    'commune' => 'Mariquina',
                    'phone' => '990394884',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => null,
                    'first_name' => 'Contreras',
                    'last_name_father' => 'Olguín',
                    'last_name_mother' => null,
                    'gender' => 'Masculino',
                    'birth_date' => null,
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Villa Entre Ríos',
                    'commune' => 'Máfil',
                    'phone' => '993886325',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.270.688-0',
                    'first_name' => 'Matías Alexander',
                    'last_name_father' => 'Ortiz',
                    'last_name_mother' => 'Labrín',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-03-12',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Por Venir',
                    'commune' => 'Máfil',
                    'phone' => '958916701',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.382.673-0',
                    'first_name' => 'Alexis Said',
                    'last_name_father' => 'Pincheira',
                    'last_name_mother' => 'Triviños',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-07-24',
                    'nationality' => 'Chilena',
                    'religion' => 'Ninguna',
                    'address' => 'Fundo Las Lomas',
                    'commune' => 'Máfil',
                    'phone' => '9992451684',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.129.727-8',
                    'first_name' => 'Lucas Daniel',
                    'last_name_father' => 'Reyes',
                    'last_name_mother' => 'Gallardo',
                    'gender' => null,
                    'birth_date' => '2009-09-22',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Los Castaños',
                    'commune' => 'Máfil',
                    'phone' => '984936705',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.654.023-5',
                    'first_name' => 'Rocío Antonio',
                    'last_name_father' => 'Riquelme',
                    'last_name_mother' => 'Rubilar',
                    'gender' => 'Masculino',
                    'birth_date' => '2011-05-28',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa Los Castaños',
                    'commune' => 'Máfil',
                    'phone' => '984226585',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.232.921-1',
                    'first_name' => 'Marcelo Eudocio',
                    'last_name_father' => 'Rodríguez',
                    'last_name_mother' => 'Tabia',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-01-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Los Pellines 342',
                    'commune' => 'Máfil',
                    'phone' => '931994957',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.653.316-6',
                    'first_name' => 'Anaís Ariel',
                    'last_name_father' => 'Sandoval',
                    'last_name_mother' => 'Mendes',
                    'gender' => 'Femenino',
                    'birth_date' => '2011-05-29',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Los Pellines 342',
                    'commune' => 'Máfil',
                    'phone' => '939182336',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.460.642-5',
                    'first_name' => 'Lizett Isidora',
                    'last_name_father' => 'Vargas',
                    'last_name_mother' => 'Lagos',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-10-25',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Calle Norte 193',
                    'commune' => 'Máfil',
                    'phone' => '936609085',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.442.033-k',
                    'first_name' => 'Agustín Mateo',
                    'last_name_father' => 'Oporto',
                    'last_name_mother' => 'Chico',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-09-21',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector Equil S/N',
                    'commune' => 'Los Lagos',
                    'phone' => '973738996',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.338.139-k',
                    'first_name' => 'Matías Nicolás',
                    'last_name_father' => 'Pérez',
                    'last_name_mother' => 'Guinel',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-05-29',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Los Pinos, Psj Los Laideles N°13',
                    'commune' => 'Los Lagos',
                    'phone' => '949884212',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],

            ];

            foreach ($students as $s) {

                $student = Student::firstOrCreate(
                    ['rut' => strtolower($s['rut'])],
                    [
                        'first_name' => $s['first_name'],
                        'last_name_father' => $s['last_name_father'],
                        'last_name_mother' => $s['last_name_mother'],
                        'gender' => $s['gender'],
                        'birth_date' => $s['birth_date'],
                        'nationality' => $s['nationality'],
                        'religion' => $s['religion'],
                        'address' => $s['address'],
                        'commune' => $s['commune'],
                        'phone' => $s['phone'],
                        'indigenous_ancestry' => !empty($s['indigenous']),
                        'indigenous_ancestry_type' => $s['indigenous'],
                        'has_health_issues' => $s['health'],
                    ]
                );

                Enrollment::firstOrCreate(
                    [
                        'student_id' => $student->id,
                        'school_year' => 2026,
                    ],
                    [
                        'course_id' => $course->id,
                        'enrollment_type' => 'Returning Student',
                        'status' => 'Pending',
                        'has_health_issues' => $s['health'],
                        'is_pie_student' => $s['pie'],
                    ]
                );
            }
        });
    }
}
