<?php

namespace Database\Seeders\Legacy;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Student;
use App\Models\Enrollment;
use App\Models\Course;

class SegundoMedioA2025Seeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            // Curso 2° Medio A – año escolar 2026
            $course = Course::whereHas('gradeLevel', function ($q) {
                $q->where('name', '2° Medio');
            })
                ->where('letter', 'A')
                ->where('school_year', 2026)
                ->firstOrFail();

            $students = [

                /* =====================================================
                 * BLOQUE 1 (1–11)
                 * ===================================================== */

                [
                    'rut' => '23.156.342-3',
                    'first_name' => 'Iván Alejandro',
                    'last_name_father' => 'Cartes',
                    'last_name_mother' => 'Carrasco',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-10-19',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Ruta 5 Sur KM 803',
                    'commune' => 'Máfil',
                    'phone' => '938937787',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.069.261-0',
                    'first_name' => 'Manuel Alejandro',
                    'last_name_father' => 'Córdova',
                    'last_name_mother' => 'Quezada',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-07-01',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Maximiliano Lara #83',
                    'commune' => 'Máfil',
                    'phone' => '933186665',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.500.129-4',
                    'first_name' => 'Matías Andrés',
                    'last_name_father' => 'Coronado',
                    'last_name_mother' => 'Sepúlveda',
                    'gender' => 'Masculino',
                    'birth_date' => '2007-09-15',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa San Luis, Pasaje San Ignacio 145, Runca',
                    'commune' => 'Máfil',
                    'phone' => '995032520',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.338.683-9',
                    'first_name' => 'Matías Ignacio',
                    'last_name_father' => 'Curín',
                    'last_name_mother' => 'Ortega',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-05-30',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Sector Mulpun, Comunidad Indígena',
                    'commune' => 'Máfil',
                    'phone' => '972718633',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.332.962-2',
                    'first_name' => 'Ariela Antonia',
                    'last_name_father' => 'Ellez',
                    'last_name_mother' => 'Rivera',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-05-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Callejón Pidey #109',
                    'commune' => 'Máfil',
                    'phone' => '993654918',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '23.063.610-9',
                    'first_name' => 'Santiago Antonio',
                    'last_name_father' => 'Ferrada',
                    'last_name_mother' => 'Muñoz',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-06-30',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Población Gabriela Mistral, Pasaje Vicuña 26',
                    'commune' => 'Máfil',
                    'phone' => '932114403',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.155.945-0',
                    'first_name' => 'Antonella Génesis',
                    'last_name_father' => 'Flandez',
                    'last_name_mother' => 'Briones',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-10-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Germán Fehlandt #79',
                    'commune' => 'Máfil',
                    'phone' => '973814264',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '22.857.596-8',
                    'first_name' => 'Constanza Alejandra',
                    'last_name_father' => 'Frías',
                    'last_name_mother' => 'Tabia',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-10-30',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa Entre Ríos, Rucapichiu #233',
                    'commune' => 'Máfil',
                    'phone' => '978647427',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.137.988-6',
                    'first_name' => 'Mayte Ayleen',
                    'last_name_father' => 'García',
                    'last_name_mother' => 'Hernández',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-10-05',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Sector Linguiento, Callejón Los Troncos Parcela 46',
                    'commune' => 'Máfil',
                    'phone' => '964214181',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.013.612-2',
                    'first_name' => 'Maira Valentina',
                    'last_name_father' => 'Guilquiruca',
                    'last_name_mother' => 'Álvarez',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-05-03',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Lo Águila S/N',
                    'commune' => 'Máfil',
                    'phone' => '965558906',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.874.515-4',
                    'first_name' => 'Ángel Fabián',
                    'last_name_father' => 'Guzmán',
                    'last_name_mother' => 'Mera',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-11-13',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Av. Pedro de Valdivia 195',
                    'commune' => 'Máfil',
                    'phone' => '951578927',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                /* =====================================================
                 * BLOQUE 2 (12–22)
                 * ===================================================== */

                [
                    'rut' => '22.856.306-4',
                    'first_name' => 'Alan Ignacio Alonso',
                    'last_name_father' => 'Henríquez',
                    'last_name_mother' => 'Flores',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-10-30',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Arturo Prat 898',
                    'commune' => 'Máfil',
                    'phone' => '983307813',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => true,
                ],
                [
                    'rut' => '23.220.990-9',
                    'first_name' => 'Maite Mariana',
                    'last_name_father' => 'Hernández',
                    'last_name_mother' => 'Baeza',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-01-03',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Lo Águila S/N',
                    'commune' => 'Máfil',
                    'phone' => '941505624',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.211.416-9',
                    'first_name' => 'Christian Rodrigo',
                    'last_name_father' => 'Jaramillo',
                    'last_name_mother' => 'Soto',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-12-22',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Villa Entre Ríos, Psje. Millahuillín #237',
                    'commune' => 'Máfil',
                    'phone' => '926332188',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.178.552-3',
                    'first_name' => 'Monserrat Alejandra',
                    'last_name_father' => 'Laurence',
                    'last_name_mother' => 'Gómez',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-11-22',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Fundo Peñaflor S/N',
                    'commune' => 'Máfil',
                    'phone' => '974819958',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.957.567-8',
                    'first_name' => 'Maximiliano Alejandro',
                    'last_name_father' => 'Lizama',
                    'last_name_mother' => 'Escare',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-02-28',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Linguento S/N',
                    'commune' => 'Máfil',
                    'phone' => '938811175',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.110.952-8',
                    'first_name' => 'Monserrat Sayem',
                    'last_name_father' => 'López',
                    'last_name_mother' => 'López',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-08-31',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Pedro Aguirre Cerda 125',
                    'commune' => 'Máfil',
                    'phone' => '992041220',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.840.434-9',
                    'first_name' => 'Benjamín Alexis',
                    'last_name_father' => 'Rapiman',
                    'last_name_mother' => 'Cisterna',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-09-30',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Pelchuquín, Sector La Punta',
                    'commune' => 'Máfil',
                    'phone' => '961178578',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.073.989-7',
                    'first_name' => 'Luis Ignacio',
                    'last_name_father' => 'Romani',
                    'last_name_mother' => 'Córdova',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-07-14',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Jaime Vera #116, Los Castaños',
                    'commune' => 'Máfil',
                    'phone' => '932062091',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.073.600-6',
                    'first_name' => 'Javier Ignacio',
                    'last_name_father' => 'Tabia',
                    'last_name_mother' => 'Bustos',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-07-07',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa Mafilita, Francisco Taladriz 340',
                    'commune' => 'Máfil',
                    'phone' => '952080940',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '22.923.032-8',
                    'first_name' => 'Maykol Alexsander',
                    'last_name_father' => 'Tabia',
                    'last_name_mother' => 'Cuevas',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-12-25',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa Entre Ríos, Psje. Curalelfu 249',
                    'commune' => 'Máfil',
                    'phone' => '935846961',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.215.535-3',
                    'first_name' => 'Sebastián Alier',
                    'last_name_father' => 'Uribe',
                    'last_name_mother' => 'Sepúlveda',
                    'gender' => 'Masculino',
                    'birth_date' => null,
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => null,
                    'commune' => 'Máfil',
                    'phone' => null,
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],

            ];

            foreach ($students as $s) {

                $student = Student::firstOrCreate(
                    ['rut' => strtolower($s['rut'])],
                    [
                        'first_name' => $s['first_name'],
                        'last_name_father' => $s['last_name_father'],
                        'last_name_mother' => $s['last_name_mother'],
                        'gender' => $s['gender'],
                        'birth_date' => $s['birth_date'],
                        'nationality' => $s['nationality'],
                        'religion' => $s['religion'],
                        'address' => $s['address'],
                        'commune' => $s['commune'],
                        'phone' => $s['phone'],
                        'indigenous_ancestry' => !empty($s['indigenous']),
                        'indigenous_ancestry_type' => $s['indigenous'],
                        'has_health_issues' => $s['health'],
                    ]
                );

                Enrollment::firstOrCreate(
                    [
                        'student_id' => $student->id,
                        'school_year' => 2026,
                    ],
                    [
                        'course_id' => $course->id,
                        'enrollment_type' => 'Returning Student',
                        'status' => 'Pending',
                        'has_health_issues' => $s['health'],
                        'is_pie_student' => $s['pie'],
                    ]
                );
            }
        });
    }
}
