<?php

namespace Database\Seeders\Legacy;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Student;
use App\Models\Enrollment;
use App\Models\Course;

class SegundoMedioB2025Seeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            // Curso 2° Medio B – año escolar 2026
            $course = Course::whereHas('gradeLevel', function ($q) {
                    $q->where('name', '2° Medio');
                })
                ->where('letter', 'B')
                ->where('school_year', 2026)
                ->firstOrFail();

            $students = [

                /* =====================================================
                 * BLOQUE 1 (1–11)
                 * ===================================================== */

                [
                    'rut' => '22.865.539-2',
                    'first_name' => 'Marcelo Tomás',
                    'last_name_father' => 'Sánchez',
                    'last_name_mother' => 'Montecinos',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-11-04',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Pelchuquin',
                    'commune' => 'Mariquina',
                    'phone' => '995354406',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.159.858-8',
                    'first_name' => 'Trinidad Pascale',
                    'last_name_father' => 'Mujica',
                    'last_name_mother' => 'Blake',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-10-31',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Fundo Las Lomas',
                    'commune' => 'Máfil',
                    'phone' => '959859982',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.520.913-8',
                    'first_name' => 'María Paz',
                    'last_name_father' => 'Llaipen',
                    'last_name_mother' => 'Quequen',
                    'gender' => 'Femenino',
                    'birth_date' => '2007-10-08',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Linguento, Los Troncos Nº25',
                    'commune' => 'Máfil',
                    'phone' => '959096473',
                    'indigenous' => 'Mapuche',
                    'health' => true,
                    'pie' => true,
                ],
                [
                    'rut' => '23.131.321-4',
                    'first_name' => 'Matías Javier',
                    'last_name_father' => 'Contreras',
                    'last_name_mother' => 'Chico',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-09-09',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector Linguento S/N',
                    'commune' => 'Los Lagos',
                    'phone' => '993501399',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.444.154-1',
                    'first_name' => 'Maximiliano Andrés',
                    'last_name_father' => 'Espinoza',
                    'last_name_mother' => 'Villalobos',
                    'gender' => 'Masculino',
                    'birth_date' => '2007-06-17',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Ruta T-324, Los Arrayanes',
                    'commune' => 'Máfil',
                    'phone' => '961412636',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '26.398.288-6',
                    'first_name' => 'Luz Angélica',
                    'last_name_father' => 'Galvis',
                    'last_name_mother' => 'Orellan',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-12-01',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'San José de la Mariquina, Santa Rosa Norte',
                    'commune' => null,
                    'phone' => '993470879',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.078.775-1',
                    'first_name' => 'Florencia Sofía',
                    'last_name_father' => 'Hermosilla',
                    'last_name_mother' => 'Gutiérrez',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-07-14',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Calle La Traca 200',
                    'commune' => 'Máfil',
                    'phone' => '928580803',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.135.365-8',
                    'first_name' => 'Juan Luis',
                    'last_name_father' => 'Alonso',
                    'last_name_mother' => 'Mariqueo Astorga',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-09-01',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Pasaje Germán Nº67',
                    'commune' => null,
                    'phone' => '995379988',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.121.876-k',
                    'first_name' => 'Jade Xiamara',
                    'last_name_father' => 'Martínez',
                    'last_name_mother' => 'Vega',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-09-13',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Sector Lo Águila',
                    'commune' => 'Máfil',
                    'phone' => '926209116',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.252.636-k',
                    'first_name' => 'Eliette Nelda',
                    'last_name_father' => 'Matus',
                    'last_name_mother' => 'Acuña',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-02-16',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Río Máfil 356, Villa Entre Ríos',
                    'commune' => 'Máfil',
                    'phone' => '976475159',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '23.229.371-3',
                    'first_name' => 'Francisco Fernando',
                    'last_name_father' => 'Meneses',
                    'last_name_mother' => 'Ojeda',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-11-30',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Fundo Los Pellines S/N',
                    'commune' => 'Máfil',
                    'phone' => '945223678',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => true,
                ],
                /* =====================================================
                 * BLOQUE 2 (12–22)
                 * ===================================================== */

                [
                    'rut' => '23.173.759-6',
                    'first_name' => 'Matías Ignacio',
                    'last_name_father' => 'Morales',
                    'last_name_mother' => 'Godoy',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-11-16',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Pasaje Los Notros',
                    'commune' => 'Máfil',
                    'phone' => '9786665327',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.408.811-6',
                    'first_name' => 'Benjamín Alexander',
                    'last_name_father' => 'Moreno',
                    'last_name_mother' => 'Gómez',
                    'gender' => 'Masculino',
                    'birth_date' => '2007-05-24',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Nilhue S/N',
                    'commune' => 'Máfil',
                    'phone' => '956984103',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.234.816-k',
                    'first_name' => 'Taref Yaiza',
                    'last_name_father' => 'Muñoz',
                    'last_name_mother' => 'Lobos',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-01-26',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Pedro de Valdivia 53',
                    'commune' => 'Mariquina',
                    'phone' => '947869930',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.296.909-1',
                    'first_name' => 'Martín Ignacio',
                    'last_name_father' => 'Padilla',
                    'last_name_mother' => 'Muñoz',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-04-07',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Pasaje Palo Santo Nº382',
                    'commune' => 'Máfil',
                    'phone' => '942768665',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.127.077-9',
                    'first_name' => 'Ángel Daniel',
                    'last_name_father' => 'Oyarzo',
                    'last_name_mother' => 'Muñoz',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-09-12',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector Las Quemas',
                    'commune' => 'Máfil',
                    'phone' => '944677073',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.848.459-8',
                    'first_name' => 'Antonella Anaís',
                    'last_name_father' => 'Patiño',
                    'last_name_mother' => 'Saez',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-10-17',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa Los Castaños Nº161',
                    'commune' => 'Máfil',
                    'phone' => '977049072',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.302.826-6',
                    'first_name' => 'Fernando Alonso',
                    'last_name_father' => 'Riquelme',
                    'last_name_mother' => 'Aguayo',
                    'gender' => 'Masculino',
                    'birth_date' => '2010-04-20',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Carlos Condell Nº1',
                    'commune' => 'Máfil',
                    'phone' => '954416677',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => true,
                ],
                [
                    'rut' => '23.195.496-1',
                    'first_name' => 'Maximiliano Antonio',
                    'last_name_father' => 'Roa',
                    'last_name_mother' => 'Loncochino',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-12-07',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Germán Felant 23',
                    'commune' => 'Máfil',
                    'phone' => '97875225',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.247.265-0',
                    'first_name' => 'Francisca Saray',
                    'last_name_father' => 'Sepúlveda',
                    'last_name_mother' => 'Beroiza',
                    'gender' => 'Femenino',
                    'birth_date' => '2010-02-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Fundo Los Pellines S/N',
                    'commune' => 'Máfil',
                    'phone' => '99343725',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '23.116.578-6',
                    'first_name' => 'Vicente Hernán',
                    'last_name_father' => 'Torres',
                    'last_name_mother' => 'Salazar',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-09-02',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector Los Águila S/N',
                    'commune' => 'Máfil',
                    'phone' => '967009190',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '23.052.540-4',
                    'first_name' => 'Selena Andrea',
                    'last_name_father' => 'Vargas',
                    'last_name_mother' => 'Flandez',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-06-02',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Maximiliano Lara Nº74',
                    'commune' => 'Máfil',
                    'phone' => '942576457',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
            ];

            foreach ($students as $s) {

                $student = Student::firstOrCreate(
                    ['rut' => strtolower($s['rut'])],
                    [
                        'first_name' => $s['first_name'],
                        'last_name_father' => $s['last_name_father'],
                        'last_name_mother' => $s['last_name_mother'],
                        'gender' => $s['gender'],
                        'birth_date' => $s['birth_date'],
                        'nationality' => $s['nationality'],
                        'religion' => $s['religion'],
                        'address' => $s['address'],
                        'commune' => $s['commune'],
                        'phone' => $s['phone'],
                        'indigenous_ancestry' => !empty($s['indigenous']),
                        'indigenous_ancestry_type' => $s['indigenous'],
                        'has_health_issues' => $s['health'],
                    ]
                );

                Enrollment::firstOrCreate(
                    [
                        'student_id' => $student->id,
                        'school_year' => 2026,
                    ],
                    [
                        'course_id' => $course->id,
                        'enrollment_type' => 'Returning Student',
                        'status' => 'Pending',
                        'has_health_issues' => $s['health'],
                        'is_pie_student' => $s['pie'],
                    ]
                );
            }
        });
    }
}
