<?php

namespace Database\Seeders\Legacy;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Student;
use App\Models\Enrollment;
use App\Models\Course;

class TerceroMedioHC2025Seeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {

            // Curso 3° Medio HC – año escolar 2026
            $course = Course::whereHas('gradeLevel', function ($q) {
                $q->where('name', '3° Medio');
            })
                ->whereNull('letter')
                ->where('specialty', 'HC')
                ->where('school_year', 2026)
                ->firstOrFail();

            $students = [

                /* =====================================================
                 * BLOQUE 1 (1–10)
                 * ===================================================== */

                [
                    'rut' => '23.390.368-1',
                    'first_name' => 'Matías Alexis',
                    'last_name_father' => 'Matus',
                    'last_name_mother' => 'Muñoz',
                    'gender' => 'Masculino',
                    'birth_date' => '2007-04-29',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Rinconada parcela 20',
                    'commune' => 'Máfil',
                    'phone' => '986228415',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.791.361-4',
                    'first_name' => 'Sayeen Aymar Poulette',
                    'last_name_father' => '',
                    'last_name_mother' => '',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-07-31',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Villa Entre Ríos, pasaje Curaleifu 233',
                    'commune' => 'Máfil',
                    'phone' => '932240848',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.622.008-9',
                    'first_name' => 'Abraham Jacob',
                    'last_name_father' => 'Coronado',
                    'last_name_mother' => 'Ñancumil',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-01-17',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Nilhue S/N',
                    'commune' => 'Máfil',
                    'phone' => '956984103',
                    'indigenous' => 'Mapuche',
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '100.707.502-9',
                    'first_name' => 'Adonaily de Jesús',
                    'last_name_father' => 'Durán',
                    'last_name_mother' => 'Montero',
                    'gender' => 'Femenino',
                    'birth_date' => '2009-01-07',
                    'nationality' => 'Venezolana',
                    'religion' => 'Evangélica',
                    'address' => 'Calle O’Higgins 105',
                    'commune' => 'Máfil',
                    'phone' => '944273152',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.951.193-9',
                    'first_name' => 'Franco Yeremi',
                    'last_name_father' => 'Guzmán',
                    'last_name_mother' => 'Montecios',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-02-04',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Sector Iñaque, huerto 7',
                    'commune' => 'Máfil',
                    'phone' => '958002015',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.847.999-3',
                    'first_name' => 'Francisco Javier',
                    'last_name_father' => 'Hernández',
                    'last_name_mother' => 'Baeza',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-10-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Lo Águila S/N',
                    'commune' => 'Máfil',
                    'phone' => '941505624',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.887.981-9',
                    'first_name' => 'Yazmin Valezca',
                    'last_name_father' => 'Higuera',
                    'last_name_mother' => 'Campos',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-12-02',
                    'nationality' => 'Chilena',
                    'religion' => 'Evangélica',
                    'address' => 'Sector Huillicoihue Bajo',
                    'commune' => 'Máfil',
                    'phone' => '934269855',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.864.044-1',
                    'first_name' => 'Antonia Betzabet',
                    'last_name_father' => 'Maldonado',
                    'last_name_mother' => 'Henríquez',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-11-01',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Los Copihues #66',
                    'commune' => 'Máfil',
                    'phone' => '990364398',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.771.475-1',
                    'first_name' => 'Pascal Antonella',
                    'last_name_father' => 'Matus',
                    'last_name_mother' => 'Escare',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-07-17',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Linguento S/N',
                    'commune' => 'Máfil',
                    'phone' => '959264122',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.698.035-0',
                    'first_name' => 'Javier Alexis',
                    'last_name_father' => 'Milla',
                    'last_name_mother' => 'Gutiérrez',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-03-22',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'El Maitén #169',
                    'commune' => 'Máfil',
                    'phone' => '979569097',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                /* =====================================================
                 * BLOQUE 2 (11–20)
                 * ===================================================== */

                [
                    'rut' => '22.785.113-9',
                    'first_name' => 'Javiera Antonia',
                    'last_name_father' => 'Ortega',
                    'last_name_mother' => 'Castro',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-03-30',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Nonoco 257, Villa Entre Ríos',
                    'commune' => 'Máfil',
                    'phone' => '920030879',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.478.321-3',
                    'first_name' => 'Ignacio Andrés',
                    'last_name_father' => 'Berrocal',
                    'last_name_mother' => 'Parada',
                    'gender' => 'Masculino',
                    'birth_date' => '2007-07-29',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Paulo Pedersen 2125',
                    'commune' => 'Mariquina',
                    'phone' => '937596931',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.926.204-1',
                    'first_name' => 'Amanda Coralay',
                    'last_name_father' => 'Peña',
                    'last_name_mother' => 'Álvarez',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-12-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Ohilip 1841',
                    'commune' => null,
                    'phone' => '921698993',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.620.516-0',
                    'first_name' => 'Benjamín Octavio',
                    'last_name_father' => 'Pérez',
                    'last_name_mother' => 'Mena',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-01-02',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Runca',
                    'commune' => 'Máfil',
                    'phone' => '942642225',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.957.056-0',
                    'first_name' => 'Javier Armando',
                    'last_name_father' => 'Reyes',
                    'last_name_mother' => 'Monsalve',
                    'gender' => 'Masculino',
                    'birth_date' => '2009-02-17',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Balmaceda 713',
                    'commune' => 'Máfil',
                    'phone' => '9715555167',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.476.093-0',
                    'first_name' => 'Arturo Ricardo',
                    'last_name_father' => 'Rodríguez',
                    'last_name_mother' => 'Tabia',
                    'gender' => 'Masculino',
                    'birth_date' => '2007-07-13',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Población Padre Hurtado, Los Pellines',
                    'commune' => 'Máfil',
                    'phone' => '921896474',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.763.516-9',
                    'first_name' => 'Ysídora Yasmin',
                    'last_name_father' => 'Sánchez',
                    'last_name_mother' => 'Milling',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-07-07',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector Putreguel',
                    'commune' => 'Máfil',
                    'phone' => '977541623',
                    'indigenous' => null,
                    'health' => true,
                    'pie' => false,
                ],
                [
                    'rut' => '22.901.862-0',
                    'first_name' => 'Benjamín Antonio',
                    'last_name_father' => 'Santana',
                    'last_name_mother' => 'Cofré',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-12-14',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Población Padre Hurtado, Los Pellines #338',
                    'commune' => 'Máfil',
                    'phone' => '995721436',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.839.586-2',
                    'first_name' => 'Maximiliano Alejandro',
                    'last_name_father' => 'Soto',
                    'last_name_mother' => 'Laurence',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-10-08',
                    'nationality' => 'Chilena',
                    'religion' => null,
                    'address' => 'Pasaje Elqui #124',
                    'commune' => 'Máfil',
                    'phone' => '976071410',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.830.417-4',
                    'first_name' => 'Gustavo Adolfo',
                    'last_name_father' => 'Vega',
                    'last_name_mother' => 'Berkhoff',
                    'gender' => 'Masculino',
                    'birth_date' => '2008-09-04',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Sector Los Aguilas',
                    'commune' => 'Máfil',
                    'phone' => '965131446',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
                [
                    'rut' => '22.790.998-6',
                    'first_name' => 'Danahe Antonella',
                    'last_name_father' => 'Vergara',
                    'last_name_mother' => 'Meneses',
                    'gender' => 'Femenino',
                    'birth_date' => '2008-08-10',
                    'nationality' => 'Chilena',
                    'religion' => 'Católica',
                    'address' => 'Villa Entre Ríos, Calle Río #420',
                    'commune' => 'Máfil',
                    'phone' => '944875767',
                    'indigenous' => null,
                    'health' => false,
                    'pie' => false,
                ],
            ];

            foreach ($students as $s) {

                $student = Student::firstOrCreate(
                    ['rut' => strtolower($s['rut'])],
                    [
                        'first_name' => $s['first_name'],
                        'last_name_father' => $s['last_name_father'],
                        'last_name_mother' => $s['last_name_mother'],
                        'gender' => $s['gender'],
                        'birth_date' => $s['birth_date'],
                        'nationality' => $s['nationality'],
                        'religion' => $s['religion'],
                        'address' => $s['address'],
                        'commune' => $s['commune'],
                        'phone' => $s['phone'],
                        'indigenous_ancestry' => !empty($s['indigenous']),
                        'indigenous_ancestry_type' => $s['indigenous'],
                        'has_health_issues' => $s['health'],
                    ]
                );

                Enrollment::firstOrCreate(
                    [
                        'student_id' => $student->id,
                        'school_year' => 2026,
                    ],
                    [
                        'course_id' => $course->id,
                        'enrollment_type' => 'Returning Student',
                        'status' => 'Pending',
                        'has_health_issues' => $s['health'],
                        'is_pie_student' => $s['pie'],
                    ]
                );
            }
        });
    }
}
